#!/bin/bash

# Creating environment file
echo -e "\e[32m::\e[0m "
echo -e "\e[32m::\e[0m Creating environment folder (/usr/share/traydrop)"

mkdir /usr/share/traydrop

echo -e "\e[32m::\e[0m Creating credentials file"
touch /usr/share/traydrop/credentials

chown root:root /usr/share/traydrop/credentials
chmod 777 /usr/share/traydrop/credentials

# Installation completed
echo -e "\e[32m::\e[0m "
echo -e "\e[32m:: Traydrop script installed successfully :)"
echo -e "\e[32m:: traydrop \e[33mhelp\e[0m"
echo -e "\e[32m::\e[0m "